### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Kracklin** [AdKats/xVotemap#1]
It won't let me upload files. So I right clicked and saved the .cs file. However, when I add it to my plugins/BF4 folder in the FTP and restart Procon, it's not in my plugins area. Do I need to add both files or just the .cs file?

**Comment by ColColonCleaner** [comment]
You should only need to add the .cs file.

Did you reboot both your layer and your client? Try restarting both of them.

**Comment by Kracklin** [comment]
repo.myrcon.com error downloading an update? The remote name could not be resolved. It won't allow me to install it.

**Comment by Kracklin** [comment]
Ok, I got it installed but it's not working like it is supposed to. I guess it's out dated.

**Comment by ColColonCleaner** [comment]
This was the latest version on myrcon before that site went down. If you have a later version then let me know about it.

**Comment by Kracklin** [comment]
No, I have the version that you posted. I finally got it installed and showing up in Procon. However, it doesn't work because I keep getting an error saying " The remote name could not be resolved. report.myrcon.com error downloading update. So I guess a new script needs to be created?

**Comment by ColColonCleaner** [comment]
Have you tried disabling automatic updates in the plugin settings?

**Comment by Kracklin** [comment]
No sir. I'll give that a go when I get home and see if that fixes it. It will say at the bottom "votemap enabled" but in the game it wouldn't throw up the voting. I'll let you know later. I'm at work right now. I have another question about this multi-balancer but it won't let me create an issue. For some odd reason, when we use adkats to !assist it will allow you to assist losing team. But if you do /fmove or /move it will move you but as soon as you spawn in, it moves you back. I guess we'll just use !assist

**Comment by ColColonCleaner** [comment]
That's an odd issue, not sure what would be causing that off the top of my head. Been a while since i looked into that code.

**Comment by Kracklin** [comment]
I used filezilla. Shadow with Best Conquest Servers helped me set
everything up. It's all working now. Branzone.com is what I use for Procon
Layer hosting, and now they have some type of issue to where I can't access
my FTP. I emailed them 4 days ago and no reply yet. Very poor CS.

**Comment by ColColonCleaner** [comment]
Glad you were able to get the help you needed. That's unfortunate that Branzone isn't working for you. I used them years ago so their service might be worse now. I should probably remove those referral links as they might be false advertising now.

**Comment by Kracklin** [comment]
Well, I mean I pay $3.00 monthly and it’s never went down. For some odd
reason, they don’t allow into FTP now. I had to use FileZilla to install
plugins. I sent them a ticket 2 days ago and they sent me an invoice? Haha
wow. They can’t even respond to my issue. I was thinking of using Fragnet.
They reply in 45 mins. We use NFO for the server.

Hey, watch that Six guy man. He’s been banning people for no reason on his
servers causing them to have a manual ban on their accounts and they can’t
get into servers. Just a friendly heads up. That’s why I didn’t respond
back.
